default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock 
   # socket: /var/run/mysqld/mysqld.sock
development:
  <<: *default
  database: lending_book_development

test:
  <<: *default
  database: lending_book_test

production:
  <<: *default
  database: lending_book_production
  username: root
  password: 
  socket: /var/run/mysqld/mysqld.sock





default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: happlyligo_development

test:
  <<: *default
  database: happlyligo_test


production:
  <<: *default
  database: happlyligo_production
  username: root
  password:
